### ISSUE TITLE
Time to sprinkel some monads

### ISSUE THREAD

**Issue by hemanth** [fp-dom/fp-select#6]
Looks like there is loads of scope to use a `mayBe` and `either` monads, what say?

**Comment by stoeffel** [comment]
Sure. Sounds good.

**Comment by stoeffel** [comment]
hmmm... how would you exactly do that?

**Comment by hemanth** [comment]
was thinking if the selects could be maybe...hmm overkill?

**Comment by stoeffel** [comment]
> hmm overkill?

hmmm... give it a try :smile:

**Comment by hemanth** [comment]
Nah, let this be as is.

**Comment by hemanth** [comment]
@stoeffel It could have been:

``` js

compose(mayBe, document.querySelectorAll(selector))

```

**Comment by stoeffel** [comment]
@hemanth 
nope, this would not work.
I assume you meant `maybe.bind` and not `mayBe`?

``` js
compose(maybe.bind, document.querySelectorAll(selector))
// is the same as
maybe.bind(document.querySelectorAll(selector))

// but maybe takes a value and a function not only a function (maybe.bind(value, function))
// if you meant maybe.return it would be the same as 
document.querySelectorAll(selector)
```

or am I understanding something wrong?
